name: Test & Deploy
on: push


jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: make install
      - run: make test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - run: gem install dpl
      - run: dpl --provider=heroku --app=git-action --api-key=${{ secrets.API_KEY_HEROKU }}




